// ===== src/lib/site-config.ts =====
// Generated by the newspaper generator. Edit here OR re-run the generator.

// --- Homepage Layout ---
export const HERO_ARTICLE_COUNT = 1;
export const GRID_COLS_CLASS = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5";
export const SHOW_DATE_ON_CARDS = true;
export const SHOW_AUTHOR_ON_CARDS = true;
export const SHOW_READING_TIME = false;
export const SHOW_CATEGORY_BADGE = true;
export const SHOW_LEAD_EXCERPT = true;
export const FEATURED_JOURNALIST = false;
export const TRENDING_SECTION = true;
export const BREAKING_NEWS_BANNER = false;
export const NEWSLETTER_BANNER_ON_HOMEPAGE = true;
export const SEARCH_BAR_IN_HEADER = false;
export const STICKY_HEADER = false;

// --- Features ---
export const NEWSLETTER_ENABLED = true;
export const READING_HISTORY_ENABLED = true;
export const SHARE_BUTTON_ENABLED = true;
export const BOOKMARKS_ENABLED = false;
export const PRINT_ENABLED = false;
export const TEXT_SIZE_ENABLED = false;
export const RELATED_ARTICLES_ENABLED = false;
export const CATEGORY_FILTER_ENABLED = true;
export const SEARCH_ENABLED = false;
export const DARK_MODE_ENABLED = false;
export const COMMENTS_ENABLED = false;

// --- Byline ---
export const SHOW_BYLINE = true;
export const LINK_JOURNALIST_PROFILE = true;
export const SHOW_JOURNALIST_PHOTO = true;
